name: 每日数据更新

on:
  schedule:
    # 每天北京时间早上 8:00 执行（UTC 0:00）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: 安装依赖
        run: npm ci
      
      - name: 执行数据更新
        run: node scripts/crawl-and-save-daily.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
      
      - name: 完成通知
        if: success()
        run: echo "✅ 数据更新成功！"
      
      - name: 失败通知
        if: failure()
        run: echo "❌ 数据更新失败，请检查日志。"
