name: 每日数据更新

on:
  schedule:
    # 每天北京时间早上 8:00 执行（UTC 0:00）
    - cron: '0 0 * * *'
    # 每天北京时间下午 13:30 执行（UTC 5:30）
    - cron: '30 5 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: 安装依赖
        run: npm ci
      
      - name: 执行数据更新
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        run: npm run update:data
      
      - name: 完成
        run: echo "✅ 数据更新成功！"
