name: Daily Data Update

# 每天0点执行，也支持手动触发
on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点执行
  workflow_dispatch:  # 支持手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run daily update script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        run: node scripts/crawl-and-save-daily.js
        
      - name: Notify success
        if: success()
        run: echo "✅ 每日数据更新任务执行成功"
        
      - name: Notify failure
        if: failure()
        run: echo "❌ 每日数据更新任务执行失败"